### ISSUE TITLE
Some octicons break the expand/collapse function

### ISSUE THREAD

**Issue by red0888** [retypeapp/retype#128]
As stated above, when some octicons are used for a folder, it breaks the collapse and expand function. For example, in https://retype.com selecting the components tab opens it but clicking again does not uncollapse the folder. It only uncollapses when clicking on the collapse icon. Also the expand animation is broken. This was not observed when using other octicons. It only seems to happen with select icons.

**Comment by red0888** [comment]
https://discord.is-into.me/y4gzJv4Zta.gif?key=2lXcpRTqP21jFh

**Comment by geoffreymcgill** [comment]
There is a `readme.md` inside the `/components` folder, so clicking on the `Components` menu item will open that index page and expand the folder. The expected result for that particular folder is to open slide open when it is clicked.

> but clicking again does not uncollapse the folder. It only uncollapses when clicking on the collapse icon.

Currently, that is the expected behaviour, I'm not convinced that is the best behaviour. I will put some thought into whether those folders with index files should collapse again when clicked. We just have to take into account that the folder is also a page. Clicking the `Components` folder will open an index page. 

The question is, if you were viewing the [Button](https://retype.com/components/button) page, then you click on the **Component** menu, would you expect the entire folder to collapse, or would you expect to see the **Components** index page? 

> Also the expand animation is broken.

I was not able to reproduce this issue.

**Comment by AndreyChechel** [comment]
> The question is, if you were viewing the Button page, then you click on the Component menu, would you expect the entire folder to collapse, or would you expect to see the Components index page?

In this scenario I'd not expect the folder to collapse. But if you were already on the Component page and the menu was expanded, it could have been collapsed by the click on the Component menu. That would make it aligned with the opposite scenario:

1. Go to the Components page
2. The menu expands
3. Click an arrow to collapse the Components menu
4. Click on the Components menu label
5. It expands, despite the page was already loaded

So the second click on the Components could have collapsed it.

**Comment by geoffreymcgill** [comment]
We have improved the functionality and user experience of this scenario. Clicking on the folder now expands and collapses the navigation if the current page is the folder default page. Feels much better now. 

The enhancement will be included in the Retype `v1.12.0` release.
