### ISSUE TITLE
Installation bug

### ISSUE THREAD

**Issue by rodrigoricky** [retypeapp/retype#146]
I am using win32.x86 but when i download it it fails.

![image](https://user-images.githubusercontent.com/89636767/134756599-480d1458-8482-4969-932b-f5fdf1e91334.png)

**Comment by geoffreymcgill** [comment]
Windows 7?

**Comment by rodrigoricky** [comment]
Yes

**Comment by fabriciomurta** [comment]
Hello!

Can you locate the **platform.js** file, make a change in it, and tell us whether it works?

You should be able to open the file for editing by going to the start menu => run... (shortcut is <kbd>win+r</kbd>) and entering this text:
```
notepad %USERPROFILE%\AppData\Roaming\npm\node_modules\retypeapp\platform.js
```

### Attempt 1

Around line 20 there will be this text:
`if (os.arch() == 'x32') {`

Change it to:

`if (os.arch() == 'x32' || os.arch() == 'ia32') {`

Save, then try running retype again.

### Attempt 2 

If it still fails, revert line 20 to what it was before, and try the same with line 14. Where it reads:

`if (os.arch() == 'x64') {`

make it read as:

`if (os.arch() == 'x64' || os.arch() == 'ia32') {`

And let us know which one worked for you. :)

### Bottomline

If you are on Windows 7, 64-bit system, you should be using the win32.x64 version of Node JS. Unless, of course, you have a specific reason to use the 32-bit one.

**Comment by rodrigoricky** [comment]
I think it's working now, but when I try to use any of the commands it doesn't do anything, or this is actually how it works.

![image](https://user-images.githubusercontent.com/89636767/134788506-c9ca69df-f034-45de-9e25-7ea5bbdaf690.png)

**Comment by fabriciomurta** [comment]
hmm it's not looking very good. Hold on, we'll prepare you a custom NPM package. We'll post back here with the package and instructions how to install it (and uninstall your current one).

**Comment by fabriciomurta** [comment]
Hello again, I have confirmed the bug by simply uninstalling nodejs 64-bit on my PC and installing the 32-bit version.

For the time being you can use retype by uninstalling it and installing platform specific version. You may try the 64-bit. Fall down to 32 bit if you have a reason to do so:

```
# uninstall current package
npm uninstall --global retypeapp

# install 64-bit version
npm install --global retypeapp-win-x64
```

In case the win-x64 doesn't work, you can then switch to the 32-bit one with this:

```
# uninstall the 64-bit version
npm uninstall --global retypeapp-win-x64

# install 32-bit package
npm install --global retypeapp-win-x86
```

Hope this helps!

**Comment by fabriciomurta** [comment]
Please note that, while Retype should work on Windows and/or NodeJS 32-bit installs, the Windows 7 OS itself is not supported. Microsoft dropped support for some time, and NodeJS also dropped support since early 2020. The latest Google Chrome might look alright with Retype, but the shipped Internet Explorer version won't work any good.

**Comment by rodrigoricky** [comment]
![image](https://user-images.githubusercontent.com/89636767/134827804-a1d187c0-c947-4927-9201-b94a90f8e758.png)

Same issue on the 32-bit pacakge.

**Comment by fabriciomurta** [comment]
Sorry, I'm afraid your windows version is beyond too old and does not work simply for being out of support.

I have a 32-bit laptop with Windows 7 here. Version is 6.1.7601; just a single build beyond yours, and I could have Retype run, installing a reasonably old NodeJS version (13.6.0 win32-x86). But there's no telling what needs to be updated in your system in order to meet the minimal software to run retype. You may try Windows Update, but again, I am afraid Microsoft is no longer providing updates for that version.

The only way I see out of this is upgrading to a supported version of Windows, or switching to Linux or Mac.

The ia32 detection bug is still there, and we'll hopefully have it fixed to the next version, but the "silent retype" issue looks beyond our reach. 😞

**Comment by geoffreymcgill** [comment]
Retype `v1.10.0` has been [released](https://github.com/retypeapp/retype/discussions/161) and should help with this issue.
