### ISSUE TITLE
Resource files not found

### ISSUE THREAD

**Issue by mss1933** [retypeapp/retype#301]
When execute "retype build", on the folder that was generate, we must add the "." in the references. For example: in "<link href="/resources/css/retype.css?v=2.0.700852413704" rel="stylesheet" data-turbo-track="reload" />" we must add the ".", "<link href="./resources/css/retype.css?v=2.0.700852413704" rel="stylesheet" data-turbo-track="reload" />"

This happens with all the resuorce references.

**Comment by geoffreymcgill** [comment]
Hi @mss1933. Can you provide some more details on how to reproduce this issue? What steps do I need to follow in order to reproduce?

Does the generated website correctly work when you run the command `retype watch`?

I think you might be trying to open the generated .html file directly from the file system without using a web server to host the files. Currently, file system browsing is not supported, although we do hope to support (or partially support) in a future release.

**Comment by mss1933** [comment]
Haa ok ok. I thought I could access from the file system. Thanks.

**Comment by geoffreymcgill** [comment]
> Haa ok ok. I thought I could access from the file system. Thanks.

We are actually working on this functionality right now. The ability to view the generated website via the file system or we might call it _offline_ mode.

The new functionality will be available in Retype `v2.3`.
