### ISSUE TITLE
Code blocks in alerts - don't work so good

### ISSUE THREAD

**Issue by benkoshy** [retypeapp/retype#385]
![image](https://user-images.githubusercontent.com/15097447/184264005-c20ad4a8-3440-4721-9731-ec59fe3a87e9.png)

Reproducible Example:

\!!!info Add Params To URLs
...by using the `:params` variable.

\```rb
@pagy, @records = pagy(Product.all, url: 'http://www.example.com/subdir',  params: {"quality": "best"})

\# links produced:
\# http://www.example.com/subdir?quality=best&amp;page=123456
\```
\!!!

![image](https://user-images.githubusercontent.com/15097447/184264191-32d45afc-39f8-4593-b6ae-7c787a8ead35.png)

**Comment by geoffreymcgill** [comment]
Looks like you might be using an older release of Retype as this issue was fixed in the `v2.0` release. See https://github.com/retypeapp/retype/issues/242.

Here is your code sample above built with the latest Retype release.

<img width="783" alt="Screen Shot 2022-08-12 at 12 10 49 AM" src="https://user-images.githubusercontent.com/62210/184295017-5d42c33c-2850-48b7-8e6a-c4e1dd2fede5.png">
 
You can [upgrade](https://retype.com/guides/getting-started/#update) your local install to the latest release or you might need to update your GitHub workflow build action to use `@latest` instead of `@v1`. 

```yml
     - uses: retypeapp/action-build@latest
     - uses: retypeapp/action-github-pages@latest
```

More details available at https://retype.com/guides/github-actions/#step-1-add-retype-actionyml-workflow. 

Hope this helps.
