### ISSUE TITLE
Using font-files

### ISSUE THREAD

**Issue by beyond9thousand** [retypeapp/retype#454]
I was attempting to use font-awesome on the page following their guide. I noticed that the icons were not being aligned with the text. I have tried styling them by defining the various properties in `_includes/head.html` but none of them seem to vertically center the icon with the following text. To be clear, the changes are taking effect, but none of them are what I need them to be.

Am I missing something?

I have tried `vertical-align: middle;` and `align-text: center;` as well as adding equal padding etc

This is relevant code at the time of opening the issue

```md
## <i class="fa-solid fa-shuffle"></i> Cross-platform
```

```html
<style>

  i {
    vertical-align: middle;
  }

  .fa-regular {
    font-size: 115%;
  }

  .fa-solid {
    font-size: 115%;
  }

  .image {
    border-radius: 12px;
  }

  figcaption {
    text-align: center;
    padding: 1% 0%;
    font-size: 90%;
  }

  @media (max-width: 550px) {
    html{
      font-size: 85%;
    }
</style>

<base target="_blank" rel="noopener" />
```
![image](https://user-images.githubusercontent.com/77363063/203928271-e6b64dc4-1332-4cf6-8d03-a06c5abe78be.png)

**Comment by beyond9thousand** [comment]
Noticed that it works if I use their pre-defined icon sizes as shown [here](https://fontawesome.com/docs/web/style/size#relative-sizing)

**Comment by beyond9thousand** [comment]
Update: Just noticed that for some reason I am unable to self-host the font files as well. Clueless here

**Comment by geoffreymcgill** [comment]
Adding any files into the `static` folder will be automatically copied to the built `output` folder location. You should be able to add files to `/static/fonts/` and they will be copied to the output. 

Hope this helps.

**Comment by beyond9thousand** [comment]
This is the folder structure I had while attempting to reference the css files as described on their guide (font awesome)

```md
- static
 - fontawesome
  - webfonts
  - css
```

Does this break any intended behaviour? (The naming)

**Comment by geoffreymcgill** [comment]
Your path is fine, but looks like the font files are not automatically included in the `output` since the font files are not considered content related files by Retype. You can easily instruct Retype to include the files by adding the font type to the `include` config in your projects `retype.yml` file. 

https://retype.com/configuration/project/#include

Please try adding the following config to your project `retype.yml` file:

```
include:
  - "*.woff2"
  - "*.ttf"
```

You can verify that a file has been copied to the `output` location by running the `retype build` command and looking for the file in the same location as your project, but within the generated `.retype` folder (or whatever location you specified in the `output` project config).

Hope this helps.

**Comment by beyond9thousand** [comment]
The files are being included but the icons still do not render unfortunately

**Comment by geoffreymcgill** [comment]
Try prefixing the path on the following two lines with `/meta`:

https://github.com/beyond9thousand/meta/blob/main/_includes/head.html#L6-L8

### Existing
```html
<link rel="stylesheet" href="/static/fonts/css/fontawesome.css" />

<link rel="stylesheet" href="/static/fonts/css/all.css" />
```
### Revised
```html
<link rel="stylesheet" href="/meta/static/fonts/css/fontawesome.css" />

<link rel="stylesheet" href="/meta/static/fonts/css/all.css" />
```

Hope this helps.

**Comment by beyond9thousand** [comment]
That worked, thanks!
