### ISSUE TITLE
Cant deploy in Netlify, 

### ISSUE THREAD

**Issue by SteffiGrim** [retypeapp/retype#468]
Hello, i need yo know if we can deploy Retype in netlify, cause i cant. [https://cheery-blini-4b949d.netlify.app/](url) This is how i see when i deployed.

**Comment by geoffreymcgill** [comment]
I have not personally deployed an app to Netlify, but it looks like it should work. The site you deployed looks fine and the `.html` is being served, but the resource files (`.js`, `.css`, etc) are not being served, which is why the site looks broken.

The generated `.html` looks good and I can't see an obvious reason why the resource files are not being served.

**Comment by geoffreymcgill** [comment]
I was able to setup and deploy a Netlify project with no issues, see https://netlify.retype.com/.

When the Retype website project is rebuilt on GitHub, the site is now auto-deployed to `retype.com` and `netlify.retype.com`. 

We created a quick draft guide for hosting on Netlify, see retype.com/hosting/netlify.
