### ISSUE TITLE
Question about built HTML.

### ISSUE THREAD

**Issue by elouann-h** [retypeapp/retype#525]
Hello everybody. I had a question concerning the compatibility with TypeDoc Markdown.
I generated my Markdown tree with Typedoc, and I wanted to make a Retype book with it (building this Markdown, of course).

But it seems there is a problem:
When I use the left navigation bar to browse among my files, each time I select a page, I get this:
<img src="https://cdn.discordapp.com/attachments/1012372287640567948/1098576223485042728/image.png">

There is my tree of files after building:
```
│   .nojekyll
│   404.html
│   index.html
│   robots.txt
│   sitemap.xml.gz
│
├───documentation
│   ├───classes
│   │   ├───command
│   │   │       index.html
│   │   │
│   │   ├───commandmanager
│   │   │       index.html
│   │   │
│   │   ├───context
│   │   │       index.html
│   │   │
│   │   ├───cooldownmanager
│   │   │       index.html
│   │   │
│   │   ├───event
│   │   │       index.html
│   │   │
│   │   ├───eventmanager
│   │   │       index.html
│   │   │
│   │   ├───interferingmanager
│   │   │       index.html
│   │   │
│   │   ├───kyaclient
│   │   │       index.html
│   │   │
│   │   └───kyaclientappearance
│   │           index.html
│   │
│   ├───enums
│   │   └───commandlocation
│   │           index.html
│   │
│   └───interfaces
│       ├───alertdata
│       │       index.html
│       │
│       ├───commandoptions
│       │       index.html
│       │
│       ├───kyaoptions
│       │       index.html
│       │
│       └───metadata
│               index.html
│
└───resources
    │   lunr.js.LICENSE.txt
    │   mermaid.js.LICENSE.txt
    │   prism.js.LICENSE.txt
    │   retype.js.LICENSE.txt
    │   retype.LICENSE.txt
    │
    ├───css
    │       retype.css
    │
    ├───fonts
    │       Poppins-Medium-Latin.woff2
    │       Poppins-Medium-LatinExt.woff2
    │       Poppins-Regular-Latin.woff2
    │       Poppins-Regular-LatinExt.woff2
    │       Poppins-SemiBold-Latin.woff2
    │       Poppins-SemiBold-LatinExt.woff2
    │
    └───js
            config.js
            lunr.js
            prism.js
            retype.js
            search.json
```
So, my question is: this problem is come from a bad configuration by me of Retype, and I have to fix it, or is it from TypeDoc configuration ? How to tell Retype to links pages on index.html of each folder ?

I'm a bit lost, and I'm new with TypeDoc and Retype, then excuse-me if I'm off-topic. Any answer will be welcomed, thanks for helping.

**Comment by geoffreymcgill** [comment]
Can you try running the command [`retype watch`](https://retype.com/guides/cli/#retype-watch)?

**Comment by geoffreymcgill** [comment]
You should be able to view that page by manually adding the `/index.html` to the end of the address. 

The issue here is **File Browsing** vs **Web Hosting**. You are trying to access and browse the website files using the file system, although websites typically require a web server to run properly.

The easiest solution would be to run the command `retype watch`. That will start up a local web server and host the Retype generated project in your local web browser.

If you do not want to use a web server, Retype can be configured for local file browsing by adding the following configs to your projects `retype.yml` file:

```yml
search:
  preload: true

generator:
  directoryIndex:
    append: true
```

If you are hosting your website on web server, remove those configs.

Additional details available at the following location:
https://github.com/retypeapp/retype/discussions/194#discussioncomment-2893450

Hope this helps.

**Comment by elouann-h** [comment]
Hey, thanks a lot, it helped. I now understand why I had this problem. Have a nice day.
