### ISSUE TITLE
Star Ratings?

### ISSUE THREAD

**Issue by latenitefilms** [retypeapp/retype#561]
Is there an existing way in Retype to do nice clean star rating like this?

https://www.w3schools.com/howto/howto_css_star_rating.asp

**Comment by latenitefilms** [comment]
I ended up solving with an included Markdown file:

```html
<!-- Font Awesome Icon Library -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
    .checked {
      color: orange;
    }
</style>
<span class="review-rating">
    <span class="fa fa-star checked"></span>
    <span class="fa fa-star checked"></span>
    <span class="fa fa-star checked"></span>
    <span class="fa fa-star checked"></span>
    <span class="fa fa-star checked"></span>
</span>
```

**Comment by geoffreymcgill** [comment]
So this is not for visitors to leave a :star: rating, but for you to just add sequential star icons in your content?

**Comment by latenitefilms** [comment]
Yes, correct. You can see it in action here:

https://fcp.cafe/workflowextensions/#braw-toolbox

I wanted something that visually looks something like on the Mac App Store.

**Comment by geoffreymcgill** [comment]
Here are a few samples just using emojis and the included icons:

```md
Rating: :star::star::star:

Rating: :star::star::star: /5

Rating: :star::star::star: of 5

Rating: :icon-star-fill::icon-star-fill::icon-star-fill::icon-star::icon-star:
```

<img width="415" alt="Screen Shot 2023-06-02 at 3 17 56 PM" src="https://github.com/retypeapp/retype/assets/62210/6333eef9-b086-4793-b9ed-ab4a402eedb4">

Then I tried your Font-Awesome sample with a couple minor changes:

```html
<!-- Font Awesome Icon Library -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
    .fa-star {
        font-size: 20px;
        color: #ccc;
    }
    .fa-star.checked {
        color: orange;
    }
</style>

Rating: <span class="fa fa-star checked"></span><span class="fa fa-star checked"></span><span class="fa fa-star checked"></span><span class="fa fa-star"></span><span class="fa fa-star"></span>
```

<img width="353" alt="Screen Shot 2023-06-02 at 3 19 44 PM" src="https://github.com/retypeapp/retype/assets/62210/75f768be-add8-4f98-a652-45fba2666f60">

It would be best to put the CSS into the **_includes/head.html** template file:

```html
<!-- Font Awesome Icon Library -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
    .fa-star {
        font-size: 20px;
        color: #ccc;
    }
    .fa-star.checked {
        color: orange;
    }
</style>
```

Then on the individual pages, you would only need to include the HTML elements:

```html
Rating: <span class="fa fa-star checked"></span><span class="fa fa-star checked"></span><span class="fa fa-star checked"></span><span class="fa fa-star"></span><span class="fa fa-star"></span>
```

which renders as the following:

<img width="296" alt="Screen Shot 2023-06-02 at 3 27 17 PM" src="https://github.com/retypeapp/retype/assets/62210/4993a761-a02e-40d1-9afa-365abe31630a">

Then I thought, maybe the Retype templating and custom data variables could clean things up.

I added the following to the project **retype.yml** file:

```yml
data:
  star: "<span class=\"fa fa-star checked\"></span>"
  unstar: "<span class=\"fa fa-star\">"
```

Then in the **.md** pages, you can simplify to the following:

```md
Rating: {{ star }}{{ star }}{{ star }}{{ unstar }}{{ unstar }}
```

which renders as the following:

<img width="296" alt="Screen Shot 2023-06-02 at 3 27 17 PM" src="https://github.com/retypeapp/retype/assets/62210/4993a761-a02e-40d1-9afa-365abe31630a">

Then I thought, how about _componentizing_ each of the ratings into its own include. So I made **_includes/rating3.md** with the following syntax:

```md
{{ star }}{{ star }}{{ star }}{{ unstar }}{{ unstar }}
```

and in the **.md** pages, you would add the following `include` statement:

```
Rating: {{ include "rating3" }}
```

which renders as the following:

<img width="296" alt="Screen Shot 2023-06-02 at 3 27 17 PM" src="https://github.com/retypeapp/retype/assets/62210/4993a761-a02e-40d1-9afa-365abe31630a">

You would make one **rating** include for each rating you would support, such as **_includes/rating5.md**:

```md
{{ star }}{{ star }}{{ star }}{{ star }}{{ star }}
```

and include in the page using:

```md
Rating: {{ include "rating5" }}
```

If using the template data variables and includes, in the future if you change how the HTML or CSS or whatever is configured, then you can easily update the templates, and then all **rating** _components_ across the project would be instantly updated. Instead of having to update the content of all Pages.

Hope this helps.

**Comment by latenitefilms** [comment]
Thanks so much for all the information and experimentation!

I did actually already come up with something similar. I have `five-stars.md`:

https://github.com/CommandPost/FCPCafe/edit/main/docs/_includes/five-stars.md

And I have the CSS in the `head.html`:

https://github.com/CommandPost/FCPCafe/blob/main/docs/_includes/head.html

I will however "steal" your CSS color and sizing tweaks! Thank you!!

**Comment by latenitefilms** [comment]
This is where I ended up for anyone who's interested:

https://fcp.cafe/workflowextensions/#user-reviews

**Comment by latenitefilms** [comment]
@geoffreymcgill - is Retype templating and custom data variables documented anywhere?

Can I use markdown in custom data variables or just HTML?

**Comment by geoffreymcgill** [comment]
>  is Retype templating and custom data variables documented anywhere?

Unfortunately, there is still much work to be done with documenting the templating the data variables. It's on my list. 

> Can I use markdown in custom data variables

Yes, you can use Markdown in the `data` variables.

The following sample demonstrates:

```yml
data:
  sample: "Hello, is **this** working? :rocket:"
```

#### sample.md

```md
# sample

{{ sample }}
```

And you can include the `data` variables inside of includes:

#### _includes/my-content.md
```md
{{ sample }}
```

#### sample.md

```md
# sample

{{ include "my-content" }}
```

Hope this helps.

**Comment by latenitefilms** [comment]
Legend, thanks for the fast reply! You beat me to even testing it myself! Appreciate it!

**Comment by latenitefilms** [comment]
Sorry, one more question... can you pass variables in?

For example, can I turn this:

```
[!badge variant="warning" target="blank" text="IMDB"](https://www.imdb.com/title/tt11881160/)
```

...into something like this:

```
{{ imdb url="https://www.imdb.com/title/tt11881160/" }}
```

**Comment by geoffreymcgill** [comment]
Yes, you can pass variables into an include. The following sample demonstrates:

#### sample.md

```md
# Sample

{{ include "imdb" url:"https://www.imdb.com/title/tt11881160/" }}
```

#### _includes/imdb.md

```md
[!badge variant="warning" target="blank" text="IMDB"]({{ $.url }})
```

The above creates the following page:

<img width="446" alt="Screenshot 2023-06-13 at 10 40 35 PM" src="https://github.com/retypeapp/retype/assets/62210/fa8cae45-23aa-4ca2-89f5-6624a120a670">

Hope this helps.
