### ISSUE TITLE
Ability for full content search when no matching headings can be found

### ISSUE THREAD

**Issue by axonasif** [retypeapp/retype#59]
Hi, a few hours back I got to know about retype and everything about it feels awesome and simple!

It would be really nice if you guys implement full content based search when no matching heading can be found.

Hoping to see this in the future ;)

Thanks!

**Comment by geoffreymcgill** [comment]
yes, agreed. Thanks for the feature request. 

We will be implementing full-context search as an option, although it will likely have to be an external hosted service. 

Maybe small sites would still be able to run full-context client-side search indexes, but once the content volume gets to a decent size, the indexing and index will need to be hosted as another service.

**Comment by axonasif** [comment]
I'm currently hosting the static site on my personal server so definitely not an issue for me :smile:

**Comment by axonasif** [comment]
> We will be implementing full-context search as an option, although it will likely have to be an external hosted service.
> 
> Maybe small sites would still be able to run full-context client-side search indexes, but once the content volume gets to a decent size, the indexing and index will need to be hosted as another service.

By the way, mdbook is yet another static site generator which powers the huge rust documentation without any noticable performance issue or whatsoever.

Maybe you guys could see how they're doing it and implement that over retype 😃

**Comment by geoffreymcgill** [comment]
> By the way, mdbook is yet another static site generator which powers the huge rust documentation without any noticable full-context search performance issue or whatsoever.

Are you referring to https://doc.rust-lang.org/std/? If no, can you share a link to the Rust docs you are referring to.

**Comment by axonasif** [comment]
> > By the way, mdbook is yet another static site generator which powers the huge rust documentation without any noticable full-context search performance issue or whatsoever.
> 
> Are you referring to https://doc.rust-lang.org/std/? If no, can you share a link to the Rust docs you are referring to.

Sorry, I should have provided links.
I was referring to [The book](https://doc.rust-lang.org/book/). [Rust by example](https://doc.rust-lang.org/stable/rust-by-example/) is quite big too. These are using [mdbook](https://rust-lang.github.io/mdBook/).

Thanks.

**Comment by geoffreymcgill** [comment]
I did a little digging to see what mdBook was using for search on those sites and it's [Elasticlunr.js](http://elasticlunr.com/) which is a fork(?) or based on [Lunr.js](http://lunrjs.com/) which is what Retype uses. So effectively, both apps mdBook and Retype are using the same client-side search library. Difference being, mdBook is configured to create a full-text index and and Retype will only search across Headings, Tags, and Categories.

That full text index required by mbBook is essentially a copy of all the content and creates an enormous search index file that must be downloaded by the client before running any search queries.

Here's the size of the search indexes for the two sites you linked to:

Site | Size
--- | ---
[The book](https://doc.rust-lang.org/book/) | [4.3 MB](https://doc.rust-lang.org/book/searchindex.json)
[Rust by example](https://doc.rust-lang.org/stable/rust-by-example/) | [1.8 MB](https://doc.rust-lang.org/stable/rust-by-example/searchindex.json)

I [forked](https://github.com/geoffreymcgill/book) the [rust-lang/book](https://github.com/rust-lang/book) project and let Retype build the project:
```
Retype finished in 1.4 seconds!
  104 pages built
  0 errors
  28 warnings
```

You can view the website Retype create for the Rust Book at https://geoffreymcgill.github.io/book/.

The search index size for that website is [22 KB](https://geoffreymcgill.github.io/book/resources/js/search.json).

Here's a chart showing the difference in index size:

![Search Index Size](https://user-images.githubusercontent.com/62210/124544857-31f01900-dde5-11eb-8a57-91df30d9e1c5.png)

Obviously this is not a fair comparison, and Retype would likely create a similar sized full-text search index, but the chart gives you an idea of the cost to download that full-text search index.

Forcing the client (browser), even mobile devices, to download 4.3 megs of data in order to perform a search is a completely unacceptable performance penalty. IMHO.

Desktop browsers with good a good connection might not notice any issues, but try that same search on a mobile device on a weak connection that you're paying high data costs for, and you're not going to be happy.

Indexing just the headings is the compromise we made with Retype in order to include lightning fast search across all clients.

That said, we can likely do better. Maybe there is a better compromise and we could somehow expand the search index by including more content. At a minimum, that would 10x our current index size, but that is still far from the 200x size of a full-text search index.

Ultimately, the most scalable solution will be using a search service. The search index and results would be hosted by another service running on another server. We have plans to implement such a service that will integrate tightly with Retype. It will be awesome.

The downside of using a search service is that the website is no longer self-contained and you have to rely on a third party service hosted elsewhere, but a compromise needs to be made somewhere if you want full-text search.

Hope this helps.

**Comment by axonasif** [comment]
Thanks for such a detained explanation, really appreciate it.
I can understand what you're saying.

For that case do you have any plans for creating a simple self-hosted search backend that we can use for retype?
Just a thought since it can be helpful for people who'd prefer to go for the simple self-hosted option instead of relying on a fancy external service :slightly_smiling_face:

**Comment by DannyBen** [comment]
Just bumped into this important discussion, especially since I am now migrating my stuff from mdbook to Retype.

> Ultimately, the most scalable solution will be using a search service. The search index and results would be hosted by another service running on another server. We have plans to implement such a service that will integrate tightly with Retype. It will be awesome.
> 
> The downside of using a search service is that the website is no longer self-contained and you have to rely on a third party service hosted elsewhere, but a compromise needs to be made somewhere if you want full-text search.

Completely agree with everything said in this discussion. Although I also would wish to have a client side full text search, I sort of stuck my head in the sand, ignoring the large index it generates.

On the other hand, I feel uneasy about search being an "external service". This feels super dirty to me - although knowing the team a little, I am sure it *will* be awesome.

Perhaps another point to think about when this feature reaches the higher levels of priority:

Maybe it would be possible to render two search indexes - one full text, and one titles only - and serve them "progressively"? Desktop gets the full experience, mobile gets the "on the go" experience?

I am not even sure it is a great idea - with all the "mobile first" movement, but perhaps it is a less drastic compromise than "lets rip this functionality out of this nice static site, and put it on a CPU server".

If the "dual index" mode is even an option - perhaps user scan configure and state that they want full index for mobile also, or small index for desktop also.

**Comment by sboklund** [comment]
@geoffreymcgill Is there a "breakpoint" in indexing between h3 and h4 headings? We get no search results for our poor h4's :)

If so, is this by design? Would it be possible to extend the indexing to include (at least) all heading levels without too big a performance loss?

**Comment by fabriciomurta** [comment]
> @geoffreymcgill Is there a "breakpoint" in indexing between h3 and h4 headings? We get no search results for our poor h4's :)
> 
> If so, is this by design? Would it be possible to extend the indexing to include (at least) all heading levels without too big a performance loss?

#166. Coming to v1.11, includes h4 to h6 in search index.

**Comment by sboklund** [comment]
Wonderful news, thanks a lot @fabriciomurta (and team)!

**Comment by RickCogley** [comment]
Glad to see it includes the headings. If the index could optionally also include any description added in front matter, that might be a help as well, in the case that the headings just are not quite what a searcher would need...

**Comment by geoffreymcgill** [comment]
We added the `description` to the search index. This new search result feature will be available in Retype `v1.12.0`. 

As well, if no custom `description` is provided by the author in the Page frontmatter config, Retype will try and create a `description` based on the initial text of the page. Typically this would be the first ~150 chars with some flexibility and logic for truncating at a good place, such as the end of sentence.

The generated `description` is already created for all pages and is used in the summary cards for pages like `/tags`, `/categories`, and  `/blog`. See https://retype.com/tags/guide/ for a sample. 

The `description` will now be added to the search index, either the generated or custom description. Custom `description` takes precedence over the Retype generated description.

The search results layout is also getting a redesign. Not sure if all the redesign will make it into `v1.12.0` but we will try.

Hope this helps.

**Comment by geoffreymcgill** [comment]
We found techniques to optimize the search index creation and have implemented full text search as the default search indexing mode for all projects.

The search results have been completely redesigned as well. 

There are now three search index modes: `full`, `partial`, and `basic`

To switch between the modes, add the following configuration to your projects `retype.yml` file:

```yml
search:
  mode: full
```

The default is `full`. If you find the search index is getting too big for your users to handle efficiently, try switching to `partial` mode:


```yml
search:
  mode: partial
```

The functionality with had in previous Retype releases would be most equivalent to the `basic` mode:

```yml
search:
  mode: basic
```

Check this out in the new Retype [`v2.0.0-preview`](https://github.com/retypeapp/retype/discussions/287#discussioncomment-2321442) release. More docs on this search mode feature are coming soon.

As well, we intend to further refine the search results and indexing functionality over time, so things should get even better with each change to this component. We would love to hear what you think of the new search functionality.

Hope this helps.

**Comment by geoffreymcgill** [comment]
Retype `v2.0` is now available.

Any thoughts on the new search?

**Comment by DannyBen** [comment]
I think the implementation is very nice. Responsive and elegant.
