### ISSUE TITLE
Styling not complete when published on GH Pages?

### ISSUE THREAD

**Issue by damianeickhoff** [retypeapp/retype#677]
I got a weird issue. The background of the menu items is gone when the page is published on GH Pages.
When I use `start` or `serve` its fine, but after publishing it, its gone.

GH Pages:
![Screenshot 2024-01-24 164347](https://github.com/retypeapp/retype/assets/12126826/de1cd03a-6a2f-40d5-9662-dca0d002e531)

Local:
![Screenshot 2024-01-24 164355](https://github.com/retypeapp/retype/assets/12126826/02b6c2ff-1c0b-4099-b0eb-9e141f98a421)

In both cases I openen the Weather Card page.

**Comment by damianeickhoff** [comment]
Small update. I figured some things out. The div is different in the local version vs the published version, but why?

Div in local version:
```html
relative flex items-center justify-between break-normal pl-3 pr-4 select-none rounded-l transition-colors ease-out duration-150 text-gray-900 dark:text-dark-250 hover:text-blue-500 dark:hover:text-blue-400
```
Div in published version:
```html
relative flex items-center justify-between break-normal pl-3 pr-4 select-none rounded-l transition-colors ease-out duration-150 text-blue-500 dark:text-blue-400 bg-blue-100 dark:bg-dark-650 rounded-l
```
If I replace the div in the dev console from my browser, it simply works.

Also is this part missing in the published version:
```
<span class="absolute right-0 h-full bg-blue-500 dark:bg-blue-400 w-px"></span>
```

**Comment by geoffreymcgill** [comment]
If you are running the same version of Retype both locally and during the GitHub Pages build process, then the output will be exactly the same. Both platforms would be running the exact software. 

But even if they were different versions, the build process should still work perfectly fine and the CSS highlighting of those elements would work also work perfectly fine when viewed in the browser.

I don't think this is an issue caused by Retype. 

So, my guess is you have some process getting in-between the GitHub Pages output and your web browser. Maybe another Action is running to post-process the HTML files? or some kind of extension is running in your web browser that is manipulating the output? or possibly you are using CloudFlare for your DNS services and have the Rocket Loader extension enabled (if yes for Rocket Loader, please [disable](https://developers.cloudflare.com/speed/optimization/content/rocket-loader/enable/))?

Hope this helps.

**Comment by damianeickhoff** [comment]
Thanks for the response.

Do what I do is, I build the page locally with 'retype build' and copy the files from the .retype folder into the documentation folder on my GH page. So I don't use the page builder of action builder.

After building the page I use 'retype serve' to check out the build and even then the issues aren't there so you would say if I copy and paste the literal files to GH it would be the the same, which isn't.

There aren't any other tools in between the developing and building the page.

I'm also not sure if this is a retype issue, but maybe you have some other ideas?

**Comment by damianeickhoff** [comment]
Moved on to Docusaurus.
