### ISSUE TITLE
Switching between two separate retypeapp web sites via links does not refresh the left pane hierarchy

### ISSUE THREAD

**Issue by ApolonTorq** [retypeapp/retype#82]
I have two independent retypeapp generated web locations. Each have a link to the other in their retype.json links section. Clicking on those links switches the main content pane (centre) and the content menu pane (right) correctly. However, the page hierarchy (left) does not get updated. It keeps the page hierarchy for the first retypeapp web location that was loaded.

**Comment by geoffreymcgill** [comment]
Hi. Thanks for the report. Are both websites hosted on the same domain (or same sub-domain) but different sub-folders? For instance, are they hosted on `example.com/site1` and `example.com/site2`?

**Comment by ApolonTorq** [comment]
Intranet, same domain with different sub-folders.

**Comment by ApolonTorq** [comment]
The problem doesn't happen if running on localhost with retype watch but does when hosted with IIS.

**Comment by geoffreymcgill** [comment]
We are running some tests to see if the new cache busting strategy that we have in the upcoming `v1.8.0` solves this scenario.

**Comment by ApolonTorq** [comment]
The browser console error displayed is:
retype.js:2 Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "turbo-frame" has already been used with this registry
    at Object.6184 (https://sen-indi-001/docs/resources/js/retype.js:2:19765)

**Comment by geoffreymcgill** [comment]
Which version of Retype are you using to build those two websites? I am assuming the latest, which is currently `v1.7.0`?

You can double check the version number using the `retype --version` command.

**Comment by geoffreymcgill** [comment]
We have reproduced the issue and have a fix working in our tests and various other scenarios. We still want to do some more research and testing, so that will take another day or so, but the fix is looking good.

We are making this issue a priority and the fix will be included in the upcoming Retype `v1.8.0` release, which should be available this week.

**Comment by ApolonTorq** [comment]
Ok, thanks.
FYI, it was running V1.7.0. It is part of an automated pipeline, so I added the version number to the build output to confirm it was the same as what I was running locally.
Thinking out loud:

- Is it worth adding build metadata to the resulting UI? Examples include the build time and the retype version. These could be made available as variables users can reference in their markdown or as a standard part of the UI like hovering over the retype logo or part of the history popup window.
- Speaking of variables, is there a documented list of values that can be referenced in markdown? I recall seeing {year} referenced somewhere.

**Comment by geoffreymcgill** [comment]
We will be adding a lot more variable support. The new functionality is planned for `v1.9.0`.

Currently, the only variable is `{{ year }}`, see 
https://retype.com/configuration/project/#copyright

The `{{ year }}` prints the current 4-digit year as a static value at build time. When the actual year rolls over, the value is not updated on the published website. We plan to change the functionality of `{{ year }}` to always print the _current_ year of the website visitor. The variable name might also change.

**Comment by fabriciomurta** [comment]
Oh, the fix for the initial issue was delivered in 1.8.0 release and we didn't post an update here!..

About the [other couple topics raised](https://github.com/retypeapp/retype/issues/82#issuecomment-883845996), I suggest we create separate issues or discussions for them or we'll simply lose track of them.

I am still not sure I should close this one, but the initial reported issue, _"Switching between two separate retypeapp web sites via links does not refresh the left pane hierarchy"_, should have been fixed in 1.8.0 and newer Retype releases. :-)
